extends: ["plugin:@typescript-eslint/recommended", "prettier"]
plugins: ["@typescript-eslint", "prettier"]
rules:
  prettier/prettier: ["error"]
parserOptions:
  ecmaVersion: 2020
  sourceType: "module"
parser: '@typescript-eslint/parser'
