name: Validate Pull Request

# This workflow verifies that the site will build for pull requests.
on: [pull_request]

jobs:
  validate-pull-request:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
          - 20.x
          - 22.x

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    # Lint and test.
    - name: install
      run: npm install
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test:cov

    # Ensure we can build.
    - name: test build
      run: |
        npm install
        npm run build

    # Upload coverage.
    - name: Upload Coverage
      uses: codecov/codecov-action@v5
      with:
        directory: ./artifacts/coverage
        token: ${{ secrets.CODECOV_TOKEN }}
